version: '3'
services:
  direwolf-1:
    build: .
    image: direwolf
    environment:
      - DEVNAME=plughw:2,0,2
    devices:
      - /dev/snd 
    ports:
      - "8000:8000"
  direwolf-2:
    build: .
    image: direwolf
    environment:
      - DEVNAME=plughw:2,1,2
    devices:
      - /dev/snd 
    ports:
      - "8001:8000"
