version: '3'
services:
  qtsoundmodem-1:
    build: .
    image: qtsoundmodem
    environment:
      - DEVNAME=hw:2,0
    devices:
      - /dev/snd 
    ports:
      - "8000:8000"
  qtsoundmodem-2:
    build: .
    image: qtsoundmodem
    environment:
      - DEVNAME=hw:2,1
    devices:
      - /dev/snd 
    ports:
      - "8001:8000"
