version: '3'
services:
  ardopc-1:
    build: .
    image: ardopc 
    environment:
      - DEVNAME=hw:2,0,1
      - LEADERLENGTH=200
    devices:
      - /dev/snd 
    ports:
      - "8515:8515"
      - "8516:8516"
  ardopc-2:
    build: .
    image: ardopc
    environment:
      - DEVNAME=hw:2,1,1
      - LEADERLENGTH=200
    devices:
      - /dev/snd 
    ports:
      - "8525:8515"
      - "8526:8516"
